cd Code/R4.4.1
Rscript buildDataSets.r
Rscript measurementModel.r
Rscript firstStageEstimation.r
Rscript secondStageEstimation.r
Rscript graphAttackProbs.r
Rscript fitNoCompetition.r
Rscript secondStageEstimation_t4t.r
Rscript modelFit.R
Rscript counterfactual_single_agent.R
Rscript counterfactual_gamma.R
Rscript counterfactual_kappa_discussion.R
