Rscript buildDataSets.r
Rscript measurementModel.r
Rscript firstStateEstimation.r
Rscript secondStageEstimation.r
Rscript figure3.R
Rscript fitNoCompetition.r
Rscript secondStageEstimation_t4t.r
Rscript modelFit.R
Rscript counterfactual_single_agent.R
Rscript counterfactual_gamma.R
Rscript counterfactual_kappa_discussion.R
