Rscript buildDataSets_byAttackType.r
Rscript counterfactual_beta.R
Rscript counterfactual_kappa.R
Rscript appendixB.R
Rscript appendixC_alternatives.r
Rscript appendixC_geographic.R
Rscript appendixD_latentMeasures.r
Rscript appendixD_PIJattacks.r
Rscript appendixD_aggregateDeaths.r
Rscript appendixD_buildraindata.r
Rscript appendixD_civilianOrNot.r
Rscript appendixD_robustness.r
Rscript appendixF.r
Rscript appendixG_VAR_comparison.r
Rscript appendixH.r
Rscript appendixI.r
Rscript appendixJ1.r
Rscript appendixJ2.r
Rscript appendixK.R
